language: java
script:
- mvn clean package
deploy: 
provider: heroku
api_key: 
  secure: MyejvmEHP+KSWZ86m8TM+PbkFiuENr9kELDtSZHU/fHuoNYWqBacKwaq8AoCHW+RP6jGnSG/61Xvb3UYRMU7wAY2l1wVBCl73h49F7yhGLiFcWRjaiys1wuNkuSAGM2bwuYezK1o6qUajtHazK9MO2FP5rZCJ6Gn3+sRZSKsI60zIJiRcCS7IwFN/84+iOxJGzOITA1GA2FUMiJ9Pc6fbHlL9hO84GtZpgAhWXskXMpL4ixt5pgBLPmYbd0jrc4TNkGIDUIvBB/EAXCZolWzPVqpaBKXzdMaEhdXcYZm3nhh460ISjlF97EMnFcI5P7NmyL6s9cNFxUsdPcrI7YsGvyKZPjkPWEwzJKjYN1Rj53ZsmF/RBIpLy7tgSjp0XVSzxc0I8YelmQ0GegstHhvGYWI7K6x3u0QxdY9+JGKZbYKf/b8s2AqYtkHmow/Q7U1n4u3/mzDUXKHyqxCvddz8eQuktIwKjdA7vtGwO8hHlJBK5nn1KTYdFu83wjTbt8B+rWJ/XEbQTHDlGkYjulF5Bek8t/mbHdU7vHHPz+j+nkQl/oraomf6a8BInAagg/Oqw6UnVMWZdsNzuEGFVvVQCR6qFv8pvsIk2PV6VQkcPH4h+JwA83llZESyV2xFNlnfDjIv57OMCRtGTNFO+QI67+K9B1EY0LxWMVaxQ78M/8=
app:
master: pi221team4
Stepanyan: pi221-stepanyan
Sheifel: pi221-sheifel
Fakhretdinova: pi221-fakhretdinova
on:
repo: mxrph/pi221team4
